import math
import calculator
result = calculator.add(5, 3)
print (result)
result = calculator.sub(5, 3)
print (result)
result = calculator.mul(5, 3)
print (result)
result = calculator.div(5, 3)
print (result)
result = calculator.mod(5, 3)
print (result)
result = calculator.power(5, 3)
print (result)
result = calculator.sqrt(25)
print (result)
result = calculator.log(10, 10)
print (result)
result = calculator.sin(math.pi/2)
print (result)
result = calculator.cos(math.pi)
print (result)
result = calculator.tan(math.pi/4)
print (result)
result = calculator.factorial(5)
print (result)
result = calculator.radians(180)
print (result)
result = calculator.degrees(math.pi)
print (result)
result = calculator.exp(1)
print (result)
result = calculator.ceil(4.2)
print (result)
result = calculator.floor(4.8)
print (result)
result = calculator.gcd(48, 18)
print (result)
result = calculator.lcm(4, 6)
print (result)
result = calculator.is_prime(7)
print (result)
result = calculator.fibonacci(10)
print (result)
result = calculator.is_even(4)
print (result)
result = calculator.is_odd(5)
print (result)
result = calculator.absolute(10)
print (result)
